project_id = "vsjijepsawdphezxbaiq"

[functions.generate-quiz-questions]
verify_jwt = false

[functions.ai-tutor]
verify_jwt = false

[functions.sync-leaderboard]
verify_jwt = false

[functions.evaluate-hr-answer]
verify_jwt = false