// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsjijepsawdphezxbaiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzamlqZXBzYXdkcGhlenhiYWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODg0NzAsImV4cCI6MjA2MDY2NDQ3MH0.TGDGGM5xfCSn4Hu0GC52wzLrMDXCbsOXme5DoAcrS3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);